# Generated by Django 5.2 on 2025-12-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_downloaded",
                    models.BooleanField(default=False, verbose_name="Скачан"),
                ),
                (
                    "is_added",
                    models.BooleanField(default=False, verbose_name="Дынные добавлены"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, null=True, verbose_name="Статус"),
                ),
            ],
            options={
                "verbose_name": "Скачанный файл",
                "verbose_name_plural": "Скачанные файлы",
            },
        ),
        migrations.CreateModel(
            name="Opsos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Оператор")),
            ],
            options={
                "verbose_name": "Оператор",
                "verbose_name_plural": "Операторы",
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Территория ГАР"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_prefix", models.CharField(max_length=5, verbose_name="Префикс")),
                (
                    "num_start",
                    models.CharField(max_length=20, verbose_name="Начиная с"),
                ),
                (
                    "num_end",
                    models.CharField(max_length=20, verbose_name="Заканчивая по"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Емкость")),
                ("opsos", models.CharField(max_length=255, verbose_name="Оператор")),
                ("region", models.CharField(max_length=500, verbose_name="Регион")),
                (
                    "territory",
                    models.TextField(
                        blank=True, null=True, verbose_name="Территория ГАР"
                    ),
                ),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
            ],
            options={
                "verbose_name": "Реестр нумерации",
                "verbose_name_plural": "Реестр нумерации",
                "unique_together": {("num_prefix", "num_start", "num_end")},
            },
        ),
        migrations.CreateModel(
            name="PhoneNorm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_prefix",
                    models.CharField(
                        db_index=True, max_length=5, verbose_name="Префикс"
                    ),
                ),
                ("num_min", models.CharField(max_length=20, verbose_name="Начиная с")),
                (
                    "num_max",
                    models.CharField(max_length=20, verbose_name="Заканчивая по"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Емкость")),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                (
                    "opsos",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abcdef.opsos",
                        verbose_name="Оператор",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abcdef.territory",
                        verbose_name="Территория ГАР",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реестр нумерации (нормализованный)",
                "verbose_name_plural": "Реестр нумерации (нормализованный)",
                "unique_together": {("num_min", "num_max")},
            },
        ),
    ]
