# Generated by Django 5.2 on 2025-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opsos",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Оператор"
            ),
        ),
    ]
