# Generated by Django 5.2 on 2025-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="Успешно"),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, null=True, verbose_name="Статус"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Попыток"),
                ),
            ],
            options={
                "verbose_name": "Скачанный файл",
                "verbose_name_plural": "Скачанные файлы",
            },
        ),
        migrations.DeleteModel(
            name="OriginFile",
        ),
    ]
