# Generated by Django 5.2 on 2025-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0002_alter_opsos_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territory",
            name="name",
            field=models.TextField(
                default="", unique=True, verbose_name="Территория ГАР"
            ),
            preserve_default=False,
        ),
    ]
