# Generated by Django 5.2 on 2025-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0002_downloadinfo_delete_originfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadinfo",
            name="link",
            field=models.URLField(default="", verbose_name="Ссылка"),
            preserve_default=False,
        ),
    ]
