# Generated by Django 5.2 on 2025-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0003_alter_territory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenorm",
            name="num_max",
            field=models.BigIntegerField(verbose_name="Заканчивая по"),
        ),
        migrations.AlterField(
            model_name="phonenorm",
            name="num_min",
            field=models.BigIntegerField(verbose_name="Начиная с"),
        ),
    ]
