# Generated by Django 5.2 on 2025-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0003_downloadinfo_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadinfo",
            name="is_success",
        ),
        migrations.AddField(
            model_name="downloadinfo",
            name="is_added",
            field=models.BooleanField(default=False, verbose_name="Добавлен"),
        ),
        migrations.AddField(
            model_name="downloadinfo",
            name="is_downloaded",
            field=models.BooleanField(default=False, verbose_name="Скачан"),
        ),
    ]
