# Generated by Django 5.2 on 2025-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0004_alter_phonenorm_num_max_alter_phonenorm_num_min"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="territory",
            options={
                "verbose_name": "Территория ГАР",
                "verbose_name_plural": "Территории ГАР",
            },
        ),
    ]
