# Generated by Django 5.2 on 2025-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "abcdef",
            "0004_remove_downloadinfo_is_success_downloadinfo_is_added_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_prefix", models.CharField(max_length=5, verbose_name="Префикс")),
                ("num_start", models.CharField(max_length=5, verbose_name="Начиная с")),
                (
                    "num_end",
                    models.CharField(max_length=5, verbose_name="Заканчивая по"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Емкость")),
                ("opsos", models.CharField(max_length=255, verbose_name="Оператор")),
                ("region", models.CharField(max_length=255, verbose_name="Регион")),
                (
                    "territory",
                    models.CharField(max_length=255, verbose_name="Территория ГАР"),
                ),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
            ],
            options={
                "verbose_name": "Реестр нумерации",
                "verbose_name_plural": "Реестр нумерации",
            },
        ),
    ]
