# Generated by Django 5.2 on 2025-12-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0005_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together={("num_prefix", "num_start", "num_end")},
        ),
    ]
