# Generated by Django 5.2 on 2025-12-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0005_alter_territory_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phonenorm",
            unique_together={("num_prefix", "num_min", "num_max")},
        ),
    ]
