# Generated by Django 5.2 on 2025-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0006_alter_phone_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="num_end",
            field=models.CharField(max_length=20, verbose_name="Заканчивая по"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="num_start",
            field=models.CharField(max_length=20, verbose_name="Начиная с"),
        ),
    ]
