# Generated by Django 5.2 on 2025-12-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0006_alter_phonenorm_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenorm",
            name="num_prefix",
            field=models.CharField(max_length=5, verbose_name="Префикс"),
        ),
    ]
