# Generated by Django 5.2 on 2025-12-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0007_alter_phone_num_end_alter_phone_num_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="territory",
            field=models.TextField(max_length=255, verbose_name="Территория ГАР"),
        ),
    ]
