# Generated by Django 5.2 on 2025-12-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0007_alter_phonenorm_num_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenorm",
            name="num_prefix",
            field=models.IntegerField(verbose_name="Префикс"),
        ),
    ]
