# Generated by Django 5.2 on 2025-12-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0008_alter_phone_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="territory",
            field=models.TextField(verbose_name="Территория ГАР"),
        ),
    ]
