# Generated by Django 5.2 on 2025-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0008_alter_phonenorm_num_prefix"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="phone",
            name="num_max",
            field=models.BigIntegerField(default=0, verbose_name="Заканчивая по"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phone",
            name="num_min",
            field=models.BigIntegerField(default=0, verbose_name="Начиная с"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="phone",
            name="num_end",
        ),
        migrations.RemoveField(
            model_name="phone",
            name="num_start",
        ),
    ]
