# Generated by Django 5.2 on 2025-12-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0009_alter_phone_territory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="territory",
        ),
    ]
