# Generated by Django 5.2 on 2025-12-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0009_alter_phone_unique_together_phone_num_max_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together={("num_prefix", "num_min", "num_max")},
        ),
    ]
