# Generated by Django 5.2 on 2025-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0010_alter_phone_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="num_prefix",
            field=models.IntegerField(verbose_name="Префикс"),
        ),
    ]
