# Generated by Django 5.2 on 2025-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0010_remove_phone_territory"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="territory",
            field=models.TextField(
                blank=True, null=True, verbose_name="Территория ГАР"
            ),
        ),
    ]
