# Generated by Django 5.2 on 2025-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abcdef", "0011_phone_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="region",
            field=models.CharField(max_length=500, verbose_name="Регион"),
        ),
    ]
